corredores_de_la_rioja_corredores_de_la_rioja_portada:
    locales: { en : /en/welcome, es : /es/portada }
    defaults: { _controller: CorredoresRiojaBundle:Default:showPortada }

corredores_de_la_rioja_corredores_de_la_rioja_homepage:
    locales: { en : /en/runners, es : /es/corredores}
    defaults: { _controller: CorredoresRiojaBundle:Default:showCorredores}


registro:
    locales: { en : /en/runners/register, es : /es/corredores/registro}
    defaults: { _controller: CorredoresRiojaBundle:Default:registro}


usuario_login:
    locales: { en : /en/runners/login, es : /es/corredores/login}
    defaults: { _controller: CorredoresRiojaBundle:Default:login }

usuario_login_check:
    path: /es/corredores/login_check
     #locales: { en : /en/login_check, es : /es/login_check}
    
usuario_logout:
    path: /es/corredores/logout
    #locales: { en : /en/logout, es : /es/logout}

mis_carreras:
     locales: { en : /en/runners/myraces, es : /es/corredores/miscarreras}
     defaults: { _controller: CorredoresRiojaBundle:Default:showMisCarreras}

      
perfil:
    locales: { en : /en/runners/profile, es : /es/corredores/perfil}
    defaults: { _controller: CorredoresRiojaBundle:Default:showPerfil}

corredores_de_la_rioja_corredores_de_la_rioja_carreras:
    locales: { en : /en/runners/races, es : /es/corredores/carreras}
    defaults: { _controller: CorredoresRiojaBundle:Default:showCarreras}


corredores_de_la_rioja_corredores_de_la_rioja_carrerasslug:  
    locales: { en : "/en/runners/race/{slug}", es : "/es/corredores/carrera/{slug}"}
    defaults: { _controller: CorredoresRiojaBundle:Default:showCarrerasSlug}


corredores_de_la_rioja_corredores_de_la_rioja_organizacion:
    locales: { en : "/en/runners/organizations/{slug}", es : "/es/corredores/organizacion/{slug}"}
    defaults: { _controller: CorredoresRiojaBundle:Default:showOrganizacionSlug}

admin_area:
    locales: { en : /en/admin, es : /es/admin}
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    

